const vendorEndPoints = {
    vendorsignUP:'/vendor/vendorVerifyEmail',
    vendorVerifyOtp:'/vendor/vendorVerifyOtp',
    vendorResendOtp:'/vendor/vendorResendOtp',
    vendorLogin:'/vendor/vendorLogin',
    vendorAddPhotos:'/vendor/addPhotos',
    vendorAddVideos:'/vendor/addVideos',
    submitStoreDetials:'/vendor/submitStoreDetials',
    editStoredetials:'/vendor/editDetails',
    getVendor:'/vendor/getVendorData',
    addUnAvaialblesDates:'/vendor/unAvailableDates',
    bringBookingRequests:'/vendor/getBookingRequests',
    getThatRequestedUser:'/vendor/getThatRequestedUser',
    acceptBookingrequest:'/vendor/acceptBookingrequest',
    fetchBookings:'/vendor/fetchBookings',
    addServices:'/vendor/addServices',
    bringChats:'/chat/getChats',
    bringVendorUserchat:'/chat/bringVendorUserChat',
    sendMessageToUser:'/chat/sendMessageTouser',
    addlocation:'/vendor/addLongLang',
    deleteService:'/vendor/deleteService',
    sendForgetEmailFromVendor:'/vendor/sendForgetMail',
    verifyForgetMail:'/vendor/verifyForgetOtp',
}

export default vendorEndPoints